server:
  port: 8087

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/smart_home_tech}
    username: ${DATASOURCE_USERNAME:cart_user}
    password: ${DATASOURCE_PASSWORD:cart_password}
  jpa:
    properties:
      hibernate:
        default_schema: shopping_cart
    hibernate:
      ddl-auto: update

logging:
  level:
    ru.yandex.practicum: DEBUG

management:
  server:
    port: 8087
  endpoints:
    web:
      exposure:
        include: "health,info"

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 5000
      warehouse:
        errorDecoder: warehouseErrorDecoder

  circuitbreaker:
    enabled: true
    group:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      warehouse:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s

  timelimiter:
    instances:
      warehouse:
        timeoutDuration: 3s