spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/smart_home_tech}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate