spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/smart_home_tech}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate

  grpc:
    client:
      hub-router:
        address: 'static://localhost:59090'
        enableKeepAlive: true
        keepAliveWithoutCalls: true
        negotiationType: plaintext