spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: aggregator-group
      auto-offset-reset: earliest
      properties:
        fetch.min.bytes: 1
        max.poll.records: 10
        max.poll.interval.ms: 30000
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/smart_home_tech}
    username: ${DATASOURCE_USERNAME:analyzer_user}
    password: ${DATASOURCE_PASSWORD:analyzer_password}
  jpa:
    properties:
      hibernate:
        default_schema: analyzer
    hibernate:
      ddl-auto: update

kafka:
  topic:
    hubs: telemetry.hubs.v1
    snapshots: telemetry.snapshots.v1

grpc:
  client:
    hub-router:
      address: 'discovery:///hub-router'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

management:
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: health